name:                aratta
version:             0.1.0.2
github:              "njohnwalker/aratta"
license:             BSD3
author:              "Nick Walker"
maintainer:          "nick.j.walker1@gmail.com"
copyright:           "2018 Nick Walker"

extra-source-files:
- README.md
- res/*/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/njohnwalker/aratta#readme>

dependencies:
- base >= 4.7 && < 5
- extra
- mtl
- lens
- text
- megaparsec
- parser-combinators
- optparse-applicative
- optparse-generic
- prettyprinter
- hashable
- containers
- filepath
- Glob
- simple-smt
- streams
- validity
- genvalidity
- genvalidity-text
- QuickCheck
- directory
- stm
- say
- unordered-containers

default-extensions:
- OverloadedStrings
- GADTs
- StandaloneDeriving
- FlexibleInstances
- FlexibleContexts
- MultiParamTypeClasses
- FunctionalDependencies
- ConstraintKinds
- DeriveGeneric
- DeriveAnyClass
- DeriveDataTypeable
- RecordWildCards
- NamedFieldPuns
- LambdaCase
- TypeFamilies
- BlockArguments
- PatternSynonyms
- ViewPatterns
- TemplateHaskell
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeOperators
- DataKinds

library:
  source-dirs:
    - src
    - smt

executables:
  houdini-verify:
    main:                Main.hs
    source-dirs:
      - app/houdini
      - app/lang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aratta

  semantic-run:
    main:                Main.hs
    source-dirs:
      - app/semantic
      - app/lang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aratta

tests:
  aratta-test:
    main:                Driver.hs
    source-dirs:
      - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aratta
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-hedgehog
    - tasty-golden
    - hspec
    - hedgehog
